name: Publish to PyPI on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: deploy
      url: https://pypi.org/p/trame-remote-control

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.8
